import { readFileSync } from 'node:fs';

import type { UsageRecord } from './types.js';

/** Per-million-token rates in USD. */
export interface ModelPricing {
  input: number;
  output: number;
  cacheWrite: number;
  cacheRead: number;
}

/**
 * Small fallback pricing table, expressed in USD per million tokens. Keys are
 * lowercase substrings matched against the recorded model id (longest match
 * wins), so `claude-opus-4-8` resolves via the `opus` entry.
 *
 * The primary table is the committed LiteLLM snapshot generated by
 * `pnpm run update-pricing` (see `src/usage/litellm-pricing.json`). This
 * fallback exists so older broad aliases (`opus`, `sonnet`, `haiku`, `gpt-5`)
 * still work when a transcript records a family name not present in the
 * snapshot. Per-deployment `config.usage.pricing` overrides still win.
 */
export const DEFAULT_PRICING: Record<string, ModelPricing> = {
  // Anthropic (Claude) — standard tier list prices.
  opus: { input: 15, output: 75, cacheWrite: 18.75, cacheRead: 1.5 },
  sonnet: { input: 3, output: 15, cacheWrite: 3.75, cacheRead: 0.3 },
  haiku: { input: 1, output: 5, cacheWrite: 1.25, cacheRead: 0.1 },
  // OpenAI (Codex) — GPT-5 family list prices. OpenAI bills cached input at a
  // reduced rate and has no separate cache-write charge, so cacheWrite mirrors
  // the input rate and cacheRead is the cached-input rate.
  'gpt-5': { input: 1.25, output: 10, cacheWrite: 1.25, cacheRead: 0.125 }
};

export type PricingOverrides = Record<string, Partial<ModelPricing>>;

interface LiteLLMSnapshot {
  prices?: Record<string, ModelPricing>;
}

const LITELLM_PRICING: Record<string, ModelPricing> = loadLiteLLMPricing();

/**
 * Resolve pricing for a model id. Matches the longest pricing key that is a
 * substring of the lowercased model id. Resolution order:
 *
 * 1. `config.usage.pricing` overrides
 * 2. the committed LiteLLM snapshot for supported models
 * 3. the small fallback `DEFAULT_PRICING` table
 *
 * Partial overrides are merged over the snapshot/fallback entry for the same
 * key. Returns `null` when nothing matches, signalling "cost unknown".
 */
export function resolvePricing(model: string, overrides: PricingOverrides = {}): ModelPricing | null {
  const id = model.toLowerCase();
  const normalizedOverrides = mergeOverrides(overrides);
  const overrideKey = bestPricingKey(id, normalizedOverrides);
  const table: Record<string, Partial<ModelPricing>> = { ...DEFAULT_PRICING, ...LITELLM_PRICING };
  const bestKey = overrideKey ?? bestPricingKey(id, table);
  if (!bestKey) {
    return null;
  }

  const merged = overrideKey ? normalizedOverrides[bestKey] : table[bestKey];
  if (
    merged.input === undefined ||
    merged.output === undefined ||
    merged.cacheWrite === undefined ||
    merged.cacheRead === undefined
  ) {
    return null;
  }
  return { input: merged.input, output: merged.output, cacheWrite: merged.cacheWrite, cacheRead: merged.cacheRead };
}

function mergeOverrides(overrides: PricingOverrides): Record<string, Partial<ModelPricing>> {
  const merged: Record<string, Partial<ModelPricing>> = {};
  for (const [key, value] of Object.entries(overrides)) {
    const normalized = key.toLowerCase();
    const base = LITELLM_PRICING[normalized] ?? DEFAULT_PRICING[normalized] ?? {};
    merged[normalized] = { ...base, ...value };
  }
  return merged;
}

function bestPricingKey(model: string, table: Record<string, Partial<ModelPricing>>): string | undefined {
  let bestKey: string | undefined;
  for (const key of Object.keys(table)) {
    if (model.includes(key.toLowerCase()) && (bestKey === undefined || key.length > bestKey.length)) {
      bestKey = key;
    }
  }
  return bestKey;
}

function loadLiteLLMPricing(): Record<string, ModelPricing> {
  try {
    const path = new URL('./litellm-pricing.json', import.meta.url);
    const parsed = JSON.parse(readFileSync(path, 'utf8')) as LiteLLMSnapshot;
    return parsed.prices ?? {};
  } catch {
    // Source checkouts before `pnpm run update-pricing` and broken package
    // installs should degrade to the small fallback table, not crash `usage`.
    return {};
  }
}

/**
 * Compute the USD cost of a usage record. When the record already carries a
 * cost (Pi), that is authoritative. Otherwise the cost is derived from the
 * pricing table; an unknown model yields `null` (token counts stay intact).
 */
export function resolveRecordCost(record: UsageRecord, overrides: PricingOverrides = {}): number | null {
  if (record.costUsd !== null) {
    return record.costUsd;
  }
  const pricing = resolvePricing(record.model, overrides);
  if (pricing === null) {
    return null;
  }
  return (
    (record.inputTokens * pricing.input +
      record.outputTokens * pricing.output +
      record.cacheWriteTokens * pricing.cacheWrite +
      record.cacheReadTokens * pricing.cacheRead) /
    1_000_000
  );
}
