import { createLogWriter } from '../log.js';

const log = createLogWriter({
  provider: 'magic-builder'
});

export const DEFAULT_MAGIC_BUILDER_BASE_URL = 'https://magic.solutionsuite.cn';
export const DEFAULT_MAGIC_BUILDER_FAAS_NAME = 'agent_presence_preview';

export interface MagicBuilderPublishOptions {
  /** Pre-rendered CommonJS function source. */
  code: string;
  /** Display name for the FaaS record. */
  name?: string;
  /** Existing record id to update in place. */
  recordId?: string;
}

export interface MagicBuilderPublishResult {
  id: string;
  recordId: string;
  faasPath: string;
  previewPath: string;
}

export interface BuildFaasOptions {
  slotId: string;
  slotBearer: string;
  /** Base URL of the slot backend the FaaS should query. */
  slotBaseUrl: string;
  /** Fallback title when the slot fetch fails. */
  fallbackTitle: string;
  /** Optional flat image_key returned alongside the title. */
  imageKey?: string;
  /** Cache control passed back to Feishu link preview. */
  expireStrategy?: '60s' | '1h' | '24h' | '1day';
}

export interface MagicBuilderInfoResult {
  title?: string;
  expireStrategy?: string;
  raw: unknown;
}

export class MagicBuilderProvider {
  constructor(
    private readonly baseUrl: string,
    private readonly token?: string
  ) {}

  /**
   * Returns the link-preview URL Feishu signature should embed. The
   * `record_id` returned by `/api/faas` is the only piece of state the
   * caller has to persist after publishing.
   */
  buildSignatureUrl(faasId: string): string {
    return new URL(`/r?fid=${encodeURIComponent(faasId)}`, this.baseUrl).toString();
  }

  buildDirectTitleUrl(title: string): string {
    const url = new URL('/r', this.baseUrl);
    url.searchParams.set('title', title);
    return url.toString();
  }

  /**
   * Render the CommonJS source for the link-preview FaaS. The function
   * runs inside magic-builder's sandbox each time Feishu pulls the link
   * preview and returns the live slot value as the title.
   */
  buildFaasCode(options: BuildFaasOptions): string {
    const expireStrategy = options.expireStrategy ?? '60s';
    const slotBaseUrl = stripTrailingSlash(options.slotBaseUrl);
    const config = {
      slotId: options.slotId,
      slotBearer: options.slotBearer,
      slotInfoUrl: `${slotBaseUrl}/api/slot/info`,
      fallbackTitle: options.fallbackTitle,
      imageKey: options.imageKey ?? '',
      expireStrategy
    };

    return `/**
 * @rivus/agent-presence preview FaaS
 *
 * Auto-generated by \`agent-presence setup --provider magic-builder\`.
 * Pulls the current slot value from the configured slot backend and
 * returns a Feishu link-preview JSON. Re-publish with the same record id
 * (\`POST /api/faas\` with \`id\`) to update.
 */
module.exports = async function (request, context) {
  const CONFIG = ${JSON.stringify(config, null, 2)};

  let title = CONFIG.fallbackTitle;
  try {
    const url = CONFIG.slotInfoUrl + "?slotId=" + encodeURIComponent(CONFIG.slotId);
    const resp = await fetch(url, {
      headers: { Authorization: "Bearer " + CONFIG.slotBearer }
    });
    if (resp.ok) {
      const data = await resp.json();
      const slot = Array.isArray(data && data.slots)
        ? data.slots.find(function (s) { return s && s.id === CONFIG.slotId; })
        : null;
      if (slot && typeof slot.value === "string" && slot.value.length > 0) {
        title = slot.value;
      }
    }
  } catch (_) {
    // Any failure falls through to the configured fallback title so Feishu
    // always renders something.
  }

  const inline = { i18n_title: { zh_cn: title } };
  if (CONFIG.imageKey) {
    inline.image_key = CONFIG.imageKey;
  }

  return new Response(
    JSON.stringify({ inline, expire_strategy: CONFIG.expireStrategy }),
    { status: 200, headers: { "Content-Type": "application/json; charset=utf-8" } }
  );
};
`;
  }

  async publishFaas(options: MagicBuilderPublishOptions): Promise<MagicBuilderPublishResult> {
    const token = this.requireToken();
    const payload: Record<string, unknown> = { code: options.code };
    if (options.name) {
      payload.name = options.name;
    }
    if (options.recordId) {
      payload.id = options.recordId;
    }

    const startedAt = Date.now();
    let response: Response;
    try {
      response = await fetch(new URL('/api/faas', this.baseUrl), {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(payload)
      });
    } catch (error) {
      logRequest('POST', '/api/faas', undefined, startedAt, 'network-error');
      throw error;
    }

    const text = await response.text();
    let parsed: unknown;
    let parseError: Error | undefined;
    try {
      parsed = text ? JSON.parse(text) : undefined;
    } catch (error) {
      parseError = error instanceof Error ? error : new Error(String(error));
    }

    if (!response.ok) {
      logRequest('POST', '/api/faas', response.status, startedAt, 'failed');
      const detail = describeError(parsed) ?? text;
      throw new Error(`magic-builder /api/faas failed: ${response.status} ${detail}`);
    }

    if (parseError) {
      logRequest('POST', '/api/faas', response.status, startedAt, 'invalid-json');
      throw new Error(`magic-builder /api/faas returned non-json response: ${text.slice(0, 200)}`);
    }

    if (!isRecord(parsed) || (typeof parsed.code === 'number' && parsed.code !== 0)) {
      logRequest('POST', '/api/faas', response.status, startedAt, 'app-error');
      const detail = describeError(parsed) ?? text;
      throw new Error(`magic-builder /api/faas returned application error: ${detail}`);
    }

    const data = isRecord(parsed.data) ? parsed.data : parsed;
    const id = pickFirstString(data, ['id', 'fid', 'record_id', 'recordId']);
    if (!id) {
      logRequest('POST', '/api/faas', response.status, startedAt, 'missing-id');
      throw new Error('magic-builder /api/faas response is missing id/record_id');
    }
    const recordId = pickFirstString(data, ['record_id', 'recordId']) ?? id;
    logRequest('POST', '/api/faas', response.status, startedAt, options.recordId ? 'updated' : 'created');

    return {
      id,
      recordId,
      faasPath: `/api/faas/${id}`,
      previewPath: `/r?fid=${id}`
    };
  }

  async invokeFaas(faasId: string): Promise<MagicBuilderInfoResult> {
    const startedAt = Date.now();
    let response: Response;
    try {
      response = await fetch(new URL(`/api/faas/${encodeURIComponent(faasId)}`, this.baseUrl));
    } catch (error) {
      logRequest('GET', `/api/faas/${faasId}`, undefined, startedAt, 'network-error');
      throw error;
    }
    const text = await response.text();
    let parsed: unknown;
    try {
      parsed = text ? JSON.parse(text) : undefined;
    } catch {
      logRequest('GET', `/api/faas/${faasId}`, response.status, startedAt, 'invalid-json');
      return { raw: text };
    }

    if (!response.ok) {
      logRequest('GET', `/api/faas/${faasId}`, response.status, startedAt, 'failed');
      throw new Error(`magic-builder /api/faas/${faasId} failed: ${response.status}`);
    }

    logRequest('GET', `/api/faas/${faasId}`, response.status, startedAt, 'ok');
    const inline = isRecord(parsed) && isRecord(parsed.inline) ? parsed.inline : undefined;
    const title = inline && isRecord(inline.i18n_title) && typeof inline.i18n_title.zh_cn === 'string' ? inline.i18n_title.zh_cn : undefined;
    const expireStrategy = isRecord(parsed) && typeof parsed.expire_strategy === 'string' ? parsed.expire_strategy : undefined;
    return { title, expireStrategy, raw: parsed };
  }

  private requireToken(): string {
    if (!this.token) {
      throw new Error(
        'missing magic-builder token; provide via MAGIC_TOKEN env var or write the token to ~/.magic-token'
      );
    }
    return this.token;
  }
}

function stripTrailingSlash(value: string): string {
  return value.replace(/\/+$/u, '');
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function describeError(parsed: unknown): string | undefined {
  if (!isRecord(parsed)) {
    return undefined;
  }
  if (typeof parsed.msg === 'string' && parsed.msg.length > 0) {
    return parsed.msg;
  }
  if (typeof parsed.message === 'string' && parsed.message.length > 0) {
    return parsed.message;
  }
  if (typeof parsed.error === 'string' && parsed.error.length > 0) {
    return parsed.error;
  }
  return undefined;
}

function pickFirstString(value: unknown, keys: string[]): string | undefined {
  if (!isRecord(value)) {
    return undefined;
  }
  for (const key of keys) {
    const candidate = value[key];
    if (typeof candidate === 'string' && candidate.length > 0) {
      return candidate;
    }
  }
  return undefined;
}

function logRequest(method: string, path: string, status: number | undefined, startedAt: number, result: string): void {
  void log
    .event({
      type: 'provider.request',
      method,
      path,
      status,
      durationMs: Date.now() - startedAt,
      result
    })
    .catch(() => {
      // diagnostic only
    });
}
