import { type RouteConfig, index, route } from "@react-router/dev/routes";

// English is the root tree; Simplified Chinese mirrors it under /zh/.
export default [
  index("routes/home.tsx"),
  route("guides/install", "routes/guides/install.tsx"),
  route("guides/quickstart", "routes/guides/quickstart.tsx"),
  route("guides/providers", "routes/guides/providers.tsx"),
  route("guides/token-usage", "routes/guides/token-usage.tsx"),
  route("guides/presence-semantics", "routes/guides/presence-semantics.tsx"),
  route("guides/render-templates", "routes/guides/render-templates.tsx"),
  route("guides/uninstall", "routes/guides/uninstall.tsx"),
  route("reference/commands", "routes/reference/commands.tsx"),
  route("reference/configuration", "routes/reference/configuration.tsx"),
  route("reference/environment-variables", "routes/reference/environment-variables.tsx"),
  route("project/architecture", "routes/project/architecture.tsx"),
  route("project/contributing", "routes/project/contributing.tsx"),
  route("project/security", "routes/project/security.tsx"),
  route("project/rfcs", "routes/project/rfcs.tsx"),
  route("project/changelog", "routes/project/changelog.tsx"),
  route("zh", "routes/zh/home.tsx"),
  route("zh/guides/install", "routes/zh/guides/install.tsx"),
  route("zh/guides/quickstart", "routes/zh/guides/quickstart.tsx"),
  route("zh/guides/providers", "routes/zh/guides/providers.tsx"),
  route("zh/guides/token-usage", "routes/zh/guides/token-usage.tsx"),
  route("zh/guides/presence-semantics", "routes/zh/guides/presence-semantics.tsx"),
  route("zh/guides/render-templates", "routes/zh/guides/render-templates.tsx"),
  route("zh/guides/uninstall", "routes/zh/guides/uninstall.tsx"),
  route("zh/reference/commands", "routes/zh/reference/commands.tsx"),
  route("zh/reference/configuration", "routes/zh/reference/configuration.tsx"),
  route("zh/reference/environment-variables", "routes/zh/reference/environment-variables.tsx"),
  route("zh/project/architecture", "routes/zh/project/architecture.tsx"),
  route("zh/project/contributing", "routes/zh/project/contributing.tsx"),
  route("zh/project/security", "routes/zh/project/security.tsx"),
  route("zh/project/rfcs", "routes/zh/project/rfcs.tsx"),
  route("zh/project/changelog", "routes/zh/project/changelog.tsx"),
] satisfies RouteConfig;
