import { Doc } from "~/components/Doc";

export function meta() {
  return [{ title: "Changelog — Agent Presence" }];
}

export default function Changelog() {
  return (
    <Doc
      locale="en"
      title="Changelog"
      source={
        <>
          <a href="https://github.com/PerfectPan/agent-presence">CHANGELOG.md</a>{" "}
          in the repository (canonical, generated by Changesets)
        </>
      }
    >
      <p>
        The canonical changelog is <code>CHANGELOG.md</code> in the repository,
        generated by Changesets. This page summarizes recent releases — read the
        source file for the full history.
      </p>

      <h2>0.6.0</h2>
      <h3>Make <code>magic-builder</code> the default provider</h3>
      <p>
        Feishu's link-preview pipeline does not reliably render the direct{" "}
        <code>l.garyyang.work</code> page, while the{" "}
        <code>magic.solutionsuite.cn</code> FaaS front-end is accepted — so a bare{" "}
        <code>agent-presence setup</code> / <code>url</code> / <code>status</code>{" "}
        now targets <code>magic-builder</code>. Slot value updates still flow to the
        l.garyyang backend (the push path is provider-agnostic), and{" "}
        <code>feishu-signature</code> remains fully supported as the underlying slot
        backend and a direct-preview alternative via{" "}
        <code>--provider feishu-signature</code>.
      </p>
      <p>
        Existing installs are unaffected: <code>login</code> persists an explicit{" "}
        <code>provider</code> in config, so the new default only applies to fresh
        setups. New users will be prompted for a Magic-Builder token during setup
        (the direct <code>feishu-signature</code> preview needs no token).
      </p>

      <h3>Token usage windows are calendar-day aligned</h3>
      <p>
        <code>今日</code> counts from local midnight (and resets at 00:00) rather
        than sliding as a <code>[now-24h, now)</code> window — which previously made
        the figure <em>decrease</em> mid-day as old activity aged out. A window of N
        days spans N local calendar days inclusive of today.
      </p>
      <p>
        A cached signature badge whose window has fully rolled over since it was
        computed (one midnight for <code>今日</code>, N days for{" "}
        <code>近N天</code>) now renders as <code>—</code> instead of a stale number,
        until the next session-boundary refresh recomputes it. The template label
        is preserved.
      </p>

      <h2>0.5.0</h2>
      <h3>Add <code>agent-presence usage</code></h3>
      <p>
        ccusage-style token consumption. Scans Claude, Codex, and Pi transcripts
        after the fact (Gemini does not persist local token usage), reports tokens
        and an estimated USD cost per source over configurable windows (default:
        last 1d and 7d). The signature can show usage via render-template variables{" "}
        <code>{"{usage}"}</code> / <code>{"{usage_1d}"}</code> /{" "}
        <code>{"{usage_7d}"}</code> / <code>{"{usage_Nd}"}</code>, or{" "}
        <code>usage.showInSignature</code> for a zero-config badge. Badges refresh
        only on session boundaries. Pricing is overridable per model in{" "}
        <code>config.usage.pricing</code>.
      </p>

      <h2>0.4.0</h2>
      <h3>Add <code>magic-builder</code> provider</h3>
      <p>
        An alternate (now default) front-end for the signature URL. Publishes a
        small CommonJS FaaS to <code>magic.solutionsuite.cn/api/faas</code> and
        emits <code>https://magic.solutionsuite.cn/r?fid=&lt;record_id&gt;</code>.
        Hooks keep writing into the l.garyyang slot; the FaaS pulls from{" "}
        <code>/api/slot/info</code> each Feishu preview refresh (default cache 60s).
      </p>
      <h3>Add Pi Coding Agent</h3>
      <p>
        Supports <code>@earendil-works/pi-coding-agent</code> as a presence source.
        Setup installs a managed extension at{" "}
        <code>~/.pi/agent/extensions/agent-presence.ts</code> bridging Pi lifecycle
        events.
      </p>

      <h2>Earlier releases</h2>
      <p>
        0.3.x added Linux platform support, China-time logfmt logging, and the
        reopen-expired-sessions fix. 0.2.x added Gemini CLI support, the{" "}
        <code>~/.agent-presence</code> home with legacy migration, and absolute hook
        command installation. 0.1.x was the initial release (macOS-only) with Clack
        prompts and the hook/state/render/provider module split.
      </p>
      <p>
        See <a href="https://github.com/PerfectPan/agent-presence">CHANGELOG.md</a>{" "}
        for the complete, exact history.
      </p>
    </Doc>
  );
}
