#!/usr/bin/env node
/**
 * Regenerate the committed LiteLLM pricing snapshot for `agent-presence usage`.
 *
 * ccusage sources model prices from LiteLLM rather than hand-maintaining a tiny
 * table. We follow that approach but keep only the model ids our supported
 * sources actually record, so the shipped snapshot stays small and reviewable.
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const LITELLM_URL =
  'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json';

const SUPPORTED_MODELS = [
  // Anthropic / Claude-style model ids seen in Claude Code and related agents.
  'claude-opus-4-8',
  'claude-opus-4-1',
  'claude-sonnet-4-6',
  'claude-sonnet-4-5',
  'claude-sonnet-5',
  'claude-haiku-4-5',
  'claude-fable-5',
  // OpenAI model ids seen in Codex and TraeX transcripts.
  'gpt-5',
  'gpt-5-codex',
  'gpt-5.4',
  'gpt-5.5',
  'gpt-5.6-sol',
  'gpt-5.6-terra',
  // DeepSeek / Gemini ids seen in opencode and TraeX transcripts.
  'deepseek-v4-pro',
  'gemini-3-flash-preview',
  'gemini-3-pro-preview',
  // Pi / Z.ai family.
  'glm-5.1'
];

const FAST_MULTIPLIERS = {
  'gpt-5.4': 2,
  'gpt-5.5': 2.5,
  'gpt-5.6-sol': 2,
  'gpt-5.6-terra': 2
};

function perMillion(value) {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    return undefined;
  }
  // Keep useful precision for very cheap cache-read rates while removing float noise.
  return Math.round(value * 1_000_000 * 1_000_000) / 1_000_000;
}

function toModelPricing(entry) {
  const input = perMillion(entry.input_cost_per_token);
  const output = perMillion(entry.output_cost_per_token);
  if (input === undefined || output === undefined) {
    return null;
  }
  const cacheWrite = perMillion(entry.cache_creation_input_token_cost) ?? input;
  const cacheWrite1h = perMillion(entry.cache_creation_input_token_cost_above_1hr);
  const longContextInput = perMillion(entry.input_cost_per_token_above_272k_tokens);
  const longContextOutput = perMillion(entry.output_cost_per_token_above_272k_tokens);
  const longContextCacheWrite = perMillion(entry.cache_creation_input_token_cost_above_272k_tokens);
  const longContextCacheRead = perMillion(entry.cache_read_input_token_cost_above_272k_tokens);
  return {
    input,
    output,
    // Providers without a separate cache-write charge bill cache creation as input.
    cacheWrite,
    ...(cacheWrite1h === undefined ? {} : { cacheWrite1h }),
    // Providers without a cache-read discount bill cached input as ordinary input.
    cacheRead: perMillion(entry.cache_read_input_token_cost) ?? input,
    ...(longContextInput === undefined &&
    longContextOutput === undefined &&
    longContextCacheWrite === undefined &&
    longContextCacheRead === undefined
      ? {}
      : {
          longContextThreshold: 272_000,
          ...(longContextInput === undefined ? {} : { longContextInput }),
          ...(longContextOutput === undefined ? {} : { longContextOutput }),
          ...(longContextCacheWrite === undefined ? {} : { longContextCacheWrite }),
          ...(longContextCacheRead === undefined ? {} : { longContextCacheRead })
        })
  };
}

async function main() {
  const response = await fetch(LITELLM_URL);
  if (!response.ok) {
    throw new Error(`failed to fetch LiteLLM pricing: HTTP ${response.status}`);
  }
  const raw = await response.json();
  const byLower = new Map(
    Object.entries(raw).map(([key, value]) => [key.toLowerCase(), { key, value }])
  );

  const prices = {};
  const missing = [];
  for (const model of SUPPORTED_MODELS) {
    const hit = byLower.get(model.toLowerCase());
    const pricing = hit ? toModelPricing(hit.value) : null;
    if (!pricing) {
      missing.push(model);
      continue;
    }
    prices[model.toLowerCase()] = {
      ...pricing,
      ...(FAST_MULTIPLIERS[model.toLowerCase()] === undefined
        ? {}
        : { fastMultiplier: FAST_MULTIPLIERS[model.toLowerCase()] })
    };
  }

  const output = {
    _comment:
      'GENERATED by scripts/update-pricing.mjs from LiteLLM. Do not edit by hand; ' +
      'change SUPPORTED_MODELS in the script, then run `pnpm run update-pricing`.',
    _source: LITELLM_URL,
    prices: Object.fromEntries(Object.keys(prices).sort().map((key) => [key, prices[key]]))
  };

  const outPath = fileURLToPath(new URL('../src/usage/litellm-pricing.json', import.meta.url));
  await writeFile(outPath, `${JSON.stringify(output, null, 2)}\n`, 'utf8');

  console.log(`wrote ${Object.keys(prices).length} model prices -> ${outPath}`);
  for (const [model, price] of Object.entries(output.prices)) {
    console.log(
      `  ${model.padEnd(28)} input=${price.input} output=${price.output} ` +
        `cacheWrite=${price.cacheWrite} cacheRead=${price.cacheRead}`
    );
  }
  if (missing.length > 0) {
    console.warn(`missing from LiteLLM snapshot: ${missing.join(', ')}`);
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
